#
# Copyright Lunatech Labs B.V. and/or licensed to Lunatech Labs B.V.
#                         under one or more contributor license agreements. See the NOTICE file
#                         distributed with this work for additional information regarding copyright
#                         ownership. Lunatech licenses this file to you under the Apache License,
#                         Version 2.0; you may not use this file except in compliance with the License.
#                         You may obtain a copy of the License at
#
#                         http://www.apache.org/licenses/LICENSE-2.0
#
#                         Unless required by applicable law or agreed to in writing, software
#                         distributed under the License is distributed on an "AS IS" BASIS,
#                         WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#                         See the License for the specific language governing permissions and
#                         limitations under the License.
#

logging:
  level:
    io.powertask.slack: DEBUG
    com.slack.api.bolt: DEBUG
    org.springframework.security: DEBUG

server:
  port: 3000


sample-process.user-id: ${SAMPLE_PROCESS_USERID}

slack:
  token: ${SLACK_TOKEN}

  bolt:
    single-team-bot-token: ${slack.token}
    signing-secret: ${SLACK_SIGNING_SECRET}

camunda:
  bpm:
    admin-user:
      id: "admin"
      password: "admin"

powertask.servicetasks.slackservice.enabled: true
powertask.slack.camunda.identitysync.group-mode: channels

powertask.slack.authentication.client-id: ${SLACK_CLIENT_ID}
powertask.slack.authentication.client-secret: ${SLACK_CLIENT_SECRET}

